<?xml version="1.0"?>
<!DOCTYPE hpc-experiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.0							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i    CDATA #REQUIRED
	      n    CDATA #REQUIRED
	      v    (raw|final|derived-incr|derived) "raw"
	      t    (inclusive|exclusive|nil) "nil"
	      fmt  CDATA #IMPLIED
	      show (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>

      <!-- Note 1: Contained Cs contain PFs and no M-->      
      <!-- Note 2: Contained PFs only contain L, S and M -->
      <!-- Note 3: The 's' attribute is not used for flat profiles -->
]>

<HPCToolkitExperiment version="2">
<Header n="jacobi">
  <Info/>
</Header>
<SecFlatProfile  i="0" n="jacobi">
<SecHeader>
 <MetricTable>
    <Metric i="0" n="WALLCLOCK (us).[0,0] (I)" v="final" t="inclusive" show="1" show-percent="1"> </Metric>
    <Metric i="1" n="WALLCLOCK (us).[0,0] (E)" v="final" t="exclusive" show="1" show-percent="1"> </Metric>
 </MetricTable>
</SecHeader>
<SecFlatProfileData>
<M n="0" v="5.473714E7"/><M n="1" v="5.473714E7"/>
<LM i="2" n="Load module /home/dxnguyen/git-rose/rose-zung/BUILD/projects/autoTuning/tests/jacobi">
<M n="0" v="5.473714E7"/><M n="1" v="5.473714E7"/>
 <F i="3" n="./jacobi.c">
 <M n="0" v="5.473714E7"/> <M n="1" v="5.473714E7"/>
  <P i="12" n="main" l="55">
  <M n="0" v="5.473714E7"/>
   <C i="-1427251183" l="72">
    <PF i="31" n="driver" l="90">
    <M n="0" v="5.473714E7"/>
    </PF>
   </C>
  </P>
  <P i="31" n="driver" l="90">
  <M n="0" v="5.473714E7"/>
   <C i="-2117186288" l="98">
    <PF i="61" n="jacobi" l="159">
    <M n="0" v="5.473714E7"/>    <M n="1" v="5.473714E7"/>
    </PF>
   </C>
  </P>
  <P i="61" n="jacobi" l="159">
  <M n="0" v="5.473714E7"/>  <M n="1" v="5.473714E7"/>
   <L i="69" l="181">
   <M n="0" v="5.473714E7"/>
    <L i="72" l="186">
    <M n="0" v="9558660.0"/>
     <L i="74" l="187">
     <M n="0" v="9558660.0"/>     <M n="1" v="9558660.0"/>
      <S i="75" l="187">
      <M n="0" v="1505950.0"/>      <M n="1" v="1505950.0"/>
      </S>
      <S i="76" l="188">
      <M n="0" v="8052710.0"/>      <M n="1" v="8052710.0"/>
      </S>
     </L>
    </L>
    <L i="77" l="190">
    <M n="0" v="4.517848E7"/>
     <L i="79" l="191">
     <M n="0" v="4.517848E7"/>     <M n="1" v="4.517848E7"/>
      <S i="80" l="191">
      <M n="0" v="1505940.0"/>      <M n="1" v="1505940.0"/>
      </S>
      <S i="81" l="193">
      <M n="0" v="1.20471E7"/>      <M n="1" v="1.20471E7"/>
      </S>
      <S i="82" l="194">
      <M n="0" v="1.05416E7"/>      <M n="1" v="1.05416E7"/>
      </S>
      <S i="83" l="196">
      <M n="0" v="1.95779E7"/>      <M n="1" v="1.95779E7"/>
      </S>
      <S i="84" l="197">
      <M n="0" v="1505940.0"/>      <M n="1" v="1505940.0"/>
      </S>
     </L>
    </L>
   </L>
  </P>
 </F>
</LM>
</SecFlatProfileData>
</SecFlatProfile>
</HPCToolkitExperiment>
