<?xml version="1.0"?>
<!DOCTYPE hpc-experiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.0							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i    CDATA #REQUIRED
	      n    CDATA #REQUIRED
	      v    (raw|final|derived-incr|derived) "raw"
	      t    (inclusive|exclusive|nil) "nil"
	      fmt  CDATA #IMPLIED
	      show (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>

      <!-- Note 1: Contained Cs contain PFs and no M-->      
      <!-- Note 2: Contained PFs only contain L, S and M -->
      <!-- Note 3: The 's' attribute is not used for flat profiles -->
]>

<HPCToolkitExperiment version="2">
<Header n="example">
  <Info/>
</Header>
<SecFlatProfile  i="0" n="example">
<SecHeader>
 <MetricTable>
    <Metric i="0" n="PAPI_L2_TCM.[0,0] (I)" v="final" t="inclusive" show="1" show-percent="1"> </Metric>
    <Metric i="1" n="PAPI_L2_TCM.[0,0] (E)" v="final" t="exclusive" show="1" show-percent="1"> </Metric>
 </MetricTable>
</SecHeader>
<SecFlatProfileData>
<M n="0" v="1.045E7"/><M n="1" v="1.045E7"/>
<LM i="2" n="Load module /home/dxnguyen/git-rose/rose-zung/BUILD/tests/roseTests/roseHPCToolkitTests/example">
<M n="0" v="1.045E7"/><M n="1" v="1.045E7"/>
 <F i="3" n="./src/home/dxnguyen/git-rose/rose-zung/tests/roseTests/roseHPCToolkitTests/data/01/example.c">
 <M n="0" v="1.045E7"/> <M n="1" v="1.045E7"/>
  <P i="45" n="main" l="67">
  <M n="0" v="1.045E7"/>
   <C i="936430121" l="89">
    <PF i="4" n="gen" l="8">
    <M n="0" v="1.0225E7"/>    <M n="1" v="1.0225E7"/>
    </PF>
   </C>
   <C i="-1029776513" l="102">
    <PF i="34" n="mv" l="52">
    <M n="0" v="225000.0"/>    <M n="1" v="225000.0"/>
    </PF>
   </C>
  </P>
  <P i="4" n="gen" l="8">
  <M n="0" v="1.0225E7"/>  <M n="1" v="1.0225E7"/>
   <L i="9" l="14">
   <M n="0" v="1.0225E7"/>   <M n="1" v="1.0225E7"/>
    <S i="10" l="14">
    <M n="0" v="100000.0"/>    <M n="1" v="100000.0"/>
    </S>
    <S i="11" l="15">
    <M n="0" v="1.0125E7"/>    <M n="1" v="1.0125E7"/>
    </S>
   </L>
  </P>
  <P i="34" n="mv" l="52">
  <M n="0" v="225000.0"/>  <M n="1" v="225000.0"/>
   <L i="38" l="56">
   <M n="0" v="225000.0"/>
    <L i="41" l="61">
    <M n="0" v="225000.0"/>    <M n="1" v="225000.0"/>
     <S i="43" l="62">
     <M n="0" v="225000.0"/>     <M n="1" v="225000.0"/>
     </S>
    </L>
   </L>
  </P>
 </F>
</LM>
</SecFlatProfileData>
</SecFlatProfile>
</HPCToolkitExperiment>
